version: "3.8"
services:
  postgres:
    container_name: database
    image: postgres
    hostname: localhost
    ports:
      - "5432:5432"
    environment:
      env_file: ".env"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    depends_on:
      - postgres
    ports:
      - "5050:80"
    environment:
      env_file: ".env"
    restart: unless-stopped

volumes:
  postgres-data:
